//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int IdBaiViet { get; set; }
        public string IdDanhMuc { get; set; }
        public Nullable<int> IdNguoiDung { get; set; }
        public string IdLoaiTin { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayXuatBan { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tiêu đề")]
        [StringLength(200, MinimumLength = 3, ErrorMessage = "Độ dài kí tự không chính xác")]
        public string TieuDe { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập mô tả")]
        [StringLength(500, MinimumLength = 3, ErrorMessage = "Độ dài kí tự không chính xác")]
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập nội dung")]
        public string NoiDung { get; set; }
        public string AnhBaiViet { get; set; }
        public string TacGia { get; set; }
        public bool TrangThai { get; set; }

        public virtual DanhMuc DanhMuc { get; set; }
        public virtual LoaiTin LoaiTin { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public BinhLuan comment { get; set; }
    }
}
