//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNangPhamMem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChucNangPhamMem()
        {
            this.VaiTro_ChucNangPhamMem = new HashSet<VaiTro_ChucNangPhamMem>();
        }
    
        public int IdChucNang { get; set; }
        public string TenChucNang { get; set; }
        public string TenForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaiTro_ChucNangPhamMem> VaiTro_ChucNangPhamMem { get; set; }
    }
}
