//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTro_ChucNangPhamMem
    {
        public int Id { get; set; }
        public Nullable<int> IdChucNang { get; set; }
        public string IdVaiTro { get; set; }
        public Nullable<bool> Xem { get; set; }
        public Nullable<bool> Them { get; set; }
        public Nullable<bool> Sua { get; set; }
        public Nullable<bool> Xoa { get; set; }
    
        public virtual ChucNangPhamMem ChucNangPhamMem { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
